In [1]:
import cvxpy as cp
import numpy as np

In [2]:
A=np.array([
    [2,1],
    [1,3],
    [1,0],
    [0,1]])
b=np.array([1,1,0,0])
c=np.array([1,1])
n=2

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize(c.T@x),
                 [A @ x >= b])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value)


The optimal value is 0.5999999999116253
A solution x is
[0.4 0.2]
A dual solution is
[4.00000000e-01 2.00000000e-01 1.18990901e-10 3.70279516e-10]


In [3]:
A=np.array([
    [2,1],
    [1,3],
    [1,0],
    [0,1]])
b=np.array([1,1,0,0])
c=np.array([-1,-1])
n=2

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize(c.T@x),
                 [A @ x >= b])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value)


The optimal value is -inf
A solution x is
None
A dual solution is
None


In [4]:
A=np.array([
    [2,1],
    [1,3],
    [1,0],
    [0,1]])
b=np.array([1,1,0,0])
c=np.array([1,0])
n=2

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize(c.T@x),
                 [A @ x >= b])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value)


The optimal value is -2.2491441767693299e-10
A solution x is
[-2.24914418e-10  1.55371590e+00]
A dual solution is
[4.91778821e-10 3.10900523e-10 1.00000000e+00 1.56903303e-10]


In [ ]:
A=np.array([
    [0,0,0,1],
    [0,0,1,0],
    [0,1,0,0],
    [1,0,0,0]
])
B=np.diag([1,-1,-1,1])

X=cp.Variable((4,4),symmetric=True)

problem=cp.Problem(cp.Minimize(cp.trace(A@X)),[X>>0,cp.trace(B@X)==1,cp.trace(X)==1])
problem.solve()
print(problem.value)
print(X.value)

-1.0000051008089093
[[ 5.00000003e-01  1.45746861e-16 -9.17043065e-17 -5.00005164e-01]
 [ 1.45746861e-16 -2.59222844e-15  2.61360502e-06 -1.45746861e-16]
 [-9.17043065e-17  2.61360502e-06 -2.59222844e-15  9.17043065e-17]
 [-5.00005164e-01 -1.45746861e-16  9.17043065e-17  5.00000003e-01]]
